#ifndef __DO_RMAHDR_
#define __DO_RMAHDR_

#ifdef __cplusplus
  extern "C" {
#endif

#define VCS_RTLIB_TLS_MODEL  __attribute__((tls_model("initial-exec")))

typedef unsigned long UP;
typedef unsigned U;
typedef unsigned char UB;
typedef unsigned char scalar;
typedef struct vec32 vec32;
typedef unsigned short US;
typedef unsigned char SVAL;
typedef unsigned char TYPEB;
typedef struct qird QIRD;
typedef unsigned char UST_e;
typedef unsigned uscope_t;
typedef U  NumLibs_t;
struct vec32 {
    U  I1;
    U  I2;
};
typedef unsigned long RP;
typedef unsigned long RO;
typedef unsigned long long ULL;
typedef U  GateCount;
typedef U  NodeCount;
typedef unsigned short HsimEdge;
typedef unsigned char HsimExprChar;
typedef struct {
    U  I694;
    RP  I695;
} RmaReceiveClock1;
typedef NodeCount  FlatNodeNum;
typedef U  InstNum;
typedef unsigned ProcessNum;
typedef unsigned long long TimeStamp64;
typedef unsigned long long TimeStamp;
typedef enum {
    PD_SING = 0,
    PD_RF = 1,
    PD_PLSE = 2,
    PD_PLSE_RF = 3,
    PD_NULL = 4
} PD_e;
typedef TimeStamp  RmaTimeStamp;
typedef TimeStamp64  RmaTimeStamp64;
typedef struct {
    int * I696;
    long long I697;
} TypeData;
struct etype {
    U  I580 :8;
    U  I581 :24;
    U  I582;
    U  I583 :1;
    U  I584 :1;
    U  I585 :1;
    U  I586 :1;
    U  I587 :1;
    U  I588 :1;
    U  I589 :1;
    U  I590 :1;
    U  I591 :1;
    U  I592 :4;
    U  I593 :1;
    U  I594 :1;
    U  I595 :1;
    U  I596 :1;
    U  I597 :1;
    U  I598 :1;
    U  I599 :1;
    U  I600 :1;
    U  I601 :2;
    U  I602 :1;
    U  I603 :2;
    U  I604 :1;
    U  I605 :1;
    U  I606 :1;
    U  I607 :1;
    U  I608 :1;
    U  I365 :1;
    U  I609;
    TypeData  * I610;
    U  I611;
    U  I612;
    U  I613 :1;
    U  I614 :1;
    U  I615 :1;
    U  I616 :1;
    U  I617 :2;
    U  I618 :2;
    U  I619 :1;
    U  I620 :1;
    U  I621 :1;
    U  I622 :1;
    U  I623 :1;
    U  I624 :1;
    U  I625 :1;
    U  I626 :1;
    U  I627 :1;
    U  I628 :15;
};
typedef union {
    double I704;
    unsigned long long I705;
    unsigned  I706[2];
} rma_clock_struct;
typedef struct eblk EBLK;
typedef int (* E_fn)(void);
typedef struct eblk {
    struct eblk * I713;
    E_fn  I714;
    struct iptmpl * I715;
    unsigned I717;
    unsigned I718;
    struct eblk * I719;
} eblk_struct;
typedef struct {
    RP  I713;
    RP  I714;
    RP  I715;
    unsigned I717;
    unsigned I718;
    RP  I719;
} RmaEblk;
typedef struct {
    RP  I713;
    RP  I714;
    RP  I715;
    unsigned I717;
    unsigned I718;
    RP  I719;
    unsigned val;
} RmaEblklq;
typedef union {
    double I704;
    unsigned long long I705;
    unsigned  I706[2];
} clock_struct;
typedef clock_struct  RmaClockStruct;
typedef struct RmaRetain_t RmaRetain;
struct RmaRetain_t {
    RP  I755;
    RmaEblk  I712;
    U  I757;
    US  I758 :1;
    US  I759 :4;
    US  I181 :2;
    US  state :2;
    US  I761 :1;
    US  I762 :2;
    US  I763 :2;
    US  fHsim :1;
    US  I563 :1;
    scalar  newval;
    scalar  I766;
    RP  I767;
};
struct retain_t {
    struct retain_t * I755;
    EBLK  I712;
    U  I757;
    US  I758 :1;
    US  I759 :4;
    US  I181 :2;
    US  state :2;
    US  I761 :1;
    US  I762 :2;
    US  I763 :2;
    US  fHsim :1;
    US  I764 :1;
    scalar  newval;
    scalar  I766;
    void * I767;
};
typedef struct MPSched MPS;
typedef struct RmaMPSched RmaMps;
struct MPSched {
    MPS  * I746;
    scalar  I747;
    scalar  I748;
    scalar  I749;
    scalar  fHsim :1;
    scalar  I181 :6;
    U  I751;
    EBLK  I752;
    void * I753;
    UP   I754[1];
};
struct RmaMPSched {
    RP  I746;
    scalar  I747;
    scalar  I748;
    scalar  I749;
    scalar  fHsim :1;
    scalar  I181 :6;
    U  I751;
    RmaEblk  I752;
    RP  I753;
    RP   I754[1];
};
typedef struct RmaMPSchedPulse RmaMpsp;
struct RmaMPSchedPulse {
    RP  I746;
    scalar  I747;
    scalar  I748;
    scalar  I749;
    scalar  I181;
    U  I751;
    RmaEblk  I752;
    scalar  I763;
    scalar  I772;
    scalar  I773;
    scalar  I774;
    U  I775;
    RmaClockStruct  I776;
    RmaClockStruct  I777;
    U  state;
    U  I778;
    RP  I715;
    RP  I779;
    RP  I780;
    RP   I754[1];
};
typedef struct MPItem MPI;
struct MPItem {
    U  * I782;
    void * I783;
};
typedef struct {
    RmaEblk  I712;
    RP  I784;
    scalar  I785;
    scalar  I763;
    scalar  I786;
} RmaTransEventHdr;
typedef struct RmaMPSchedPulseNewCsdf RmaMpspNewCsdf;
struct RmaMPSchedPulseNewCsdf {
    RP  I746;
    scalar  I747;
    scalar  I748;
    scalar  I749;
    scalar  fHsim :1;
    scalar  I181 :6;
    U  I751;
    RmaEblk  I752;
    scalar  I763;
    scalar  I772;
    scalar  I773;
    scalar  I774;
    U  state :4;
    U  I788 :28;
    RmaClockStruct  I776;
    RmaClockStruct  I777;
    RP  I789;
    RP  I715;
    RP  I790;
    RP   I754[1];
};
typedef struct red_t {
    U  I791;
    U  I792;
    U  I673;
} RED;
typedef struct predd {
    PD_e  I181;
    RED   I793[0];
} PREDD;
union rhs_value {
    vec32  I794;
    scalar  I785;
    vec32  * I763;
    double I795;
    U  I796;
};
typedef struct nbs_t {
    struct nbs_t * I797;
    struct nbs_t * I799;
    void (* I800)(struct nbs_t * I767);
    U  I801 :1;
    U  I802 :1;
    U  I803 :1;
    U  I804 :1;
    U  I805 :1;
    U  I806 :1;
    U  I807 :26;
    U  I808;
    void * I809;
    union rhs_value I810;
    vec32  I704;
    union {
        struct nbs_t * first;
        struct nbs_t * last;
    } I812;
} NBS;
typedef struct {
    RP  I813;
    RP  I779;
    RP  I715;
    RP  I780;
    RmaEblk  I712;
    RmaEblk  I814;
    RP  I815;
    scalar  I785;
    scalar  I763;
    char state;
    uscope_t  I816;
    U  I817;
    RP  I818;
    scalar  I772;
    scalar  I773;
    scalar  I774;
    RmaClockStruct  I776;
    RmaClockStruct  I777;
    RP  I753;
} RmaPulse;
typedef enum {
    QIRDModuleC = 1,
    QIRDSVPackageC = 2,
    QIRDSpiceModuleC = 3
} QIRDModuleType;
typedef struct {
    U  I822 :1;
    U  I823 :1;
    U  I824 :1;
    U  I825 :1;
    U  I826 :1;
    U  I827 :1;
    U  I828 :1;
    U  I829 :1;
    U  I830 :1;
    U  I831 :1;
    U  I832 :1;
    U  I833 :1;
    U  I834 :1;
    U  I835 :1;
    U  I836 :1;
    U  I837 :1;
    U  I838 :1;
    U  I839 :1;
    QIRDModuleType  I840 :2;
    U  I841 :1;
    U  I842 :1;
    U  I843 :1;
    U  I844 :1;
    U  I845 :1;
    U  I846 :1;
    U  I847 :1;
    U  I848 :1;
    U  I849 :1;
    U  I850 :1;
    U  I851 :1;
    U  I852 :1;
    U  I853 :1;
    U  I854 :1;
    U  I855 :1;
    U  I856 :1;
    U  I857 :1;
    U  I858 :1;
} BitFlags;
struct qird {
    US  I4;
    US  I5;
    U  I6;
    U  I7;
    char * I8;
    char * I9;
    U  * I10;
    char * I11;
    char * I12;
    U  I13;
    U  I14;
    struct vcd_rt * I15;
    U  I17;
    struct _vcdOffset_rt * I18;
    U  I20;
    U  I21;
    U  * I22;
    U  * I23;
    void * I24;
    void * I25;
    U  I26;
    int I27;
    UP  I28;
    U  I29;
    U  I30;
    U  I31;
    UP  I32;
    U  * I33;
    UP  I34;
    U  I35;
    BitFlags  I36;
    U  I37;
    U  I38;
    U  I39;
    U  I40;
    U  I41;
    U  * I42;
    U  I43;
    U  * I44;
    U  I45;
    U  I46;
    U  I47;
    U  I48;
    U  I49;
    U  I50;
    U  I51;
    U  * I52;
    U  * I53;
    U  I54;
    U  I55;
    U  * I56;
    U  I57;
    U  * I58;
    U  I59;
    U  I60;
    U  I61;
    U  I62;
    U  * I63;
    U  I64;
    U  * I65;
    U  I66;
    U  I67;
    U  I68;
    U  I69;
    U  I70;
    U  I71;
    U  * I72;
    char * I73;
    U  I74;
    U  I75;
    U  I76;
    U  I77;
    U  I78;
    U  * I79;
    U  I80;
    U  I81;
    U  I82;
    UP  * I83;
    U  I84;
    U  I85;
    U  I86;
    U  I87;
    U  I88;
    U  I89;
    U  * I90;
    U  I91;
    U  I92;
    U  * I93;
    U  * I94;
    U  * I95;
    U  * I96;
    U  * I97;
    U  I98;
    U  I99;
    struct taskInfo * I100;
    U  I102;
    U  I103;
    U  I104;
    int * I105;
    U  * I106;
    UP  * I107;
    U  * I108;
    U  I109;
    U  I110;
    U  I111;
    U  I112;
    U  I113;
    struct qrefer * I114;
    U  * I116;
    unsigned * I117;
    void * I118;
    U  I119;
    U  I120;
    struct classStaticReferData * I121;
    U  I123;
    U  * I124;
    U  I125;
    U  * I126;
    U  I127;
    struct wakeupInfoStruct * I128;
    U  I130;
    U  I131;
    U  I132;
    U  * I133;
    U  I134;
    U  * I135;
    U  I136;
    U  I137;
    U  I138;
    U  * I139;
    U  I140;
    U  * I141;
    U  I142;
    U  I143;
    U  * I144;
    U  I145;
    U  I146;
    U  * I147;
    U  * I148;
    U  * I149;
    U  I150;
    U  I151;
    U  I152;
    U  I153;
    U  I154;
    struct qrefee * I155;
    U  * I157;
    U  I158;
    struct qdefrefee * I159;
    U  * I161;
    int (* I162)(void);
    char * I163;
    U  I164;
    U  I165;
    void * I166;
    void * I167;
    NumLibs_t  I168;
    char * I169;
    U  * I170;
    U  I171;
    U  I172;
    U  I173;
    U  I174;
    U  I175;
    U  * I176;
    U  * I177;
    int I178;
    struct clock_load * I179;
    int I194;
    struct clock_data * I195;
    int I211;
    struct clock_hiconn * I212;
    U  I216;
    U  I217;
    U  I218;
    U  I219;
    U  * I220;
    U  * I221;
    U  I222;
    void * I223;
    U  I224;
    U  I225;
    UP  * I226;
    void * I227;
    U  I228;
    UP  * I229;
    U  * I230;
    int (* I231)(void);
    U  * I232;
    UP  * I233;
    U  * I234;
    U  I235 :1;
    U  I236 :31;
    U  I237;
    U  I238;
    UP  * I239;
    U  * I240;
    U  I241 :1;
    U  I242 :1;
    U  I243 :1;
    U  I244 :1;
    U  I245 :28;
    U  I246;
    U  I247;
    U  I248;
    U  I249 :31;
    U  I250 :1;
    UP  * I251;
    UP  * I252;
    U  * I253;
    U  * I254;
    U  * I255;
    UP  * I256;
    UP  * I257;
    UP  * I258;
    U  * I259;
    UP  * I260;
    UP  * I261;
    UP  * I262;
    UP  * I263;
    char * I264;
    U  I265;
    U  I266;
    U  I267;
    UP  * I268;
    U  I269;
    UP  * I270;
    UP  * I271;
    UP  * I272;
    UP  * I273;
    UP  * I274;
    UP  * I275;
    UP  * I276;
    UP  * I277;
    UP  * I278;
    UP  * I279;
    UP  * I280;
    UP  * I281;
    UP  * I282;
    U  * I283;
    U  * I284;
    UP  * I285;
    U  I286;
    U  I287;
    U  I288;
    U  I289;
    U  I290;
    U  I291;
    U  I292;
    U  I293;
    char * I294;
    U  * I295;
    U  I296;
    U  I297;
    U  I298;
    U  I299;
    U  I300;
    UP  * I301;
    UP  * I302;
    UP  * I303;
    UP  * I304;
    struct daidirInfo * I305;
    struct vcs_tftable * I307;
    U  I309;
    UP  * I310;
    UP  * I311;
    U  I312;
    U  I313;
    U  I314;
    UP  * I315;
    U  * I316;
    UP  * I317;
    UP  * I318;
    struct qird_hil_data * I319;
    UP  (* I321)(void);
    UP  (* I322)(void);
    UP  (* I323)(void);
    UP  (* I324)(void);
    UP  (* I325)(void);
    int * I326;
    int (* I327)(void);
    char * I328;
    UP  * I329;
    UP  * I330;
    UP  (* I331)(void);
    int (* I332)(void);
    int * I333;
    int (* I334)(void);
    int * I335;
    char * I336;
    U  * I337;
    U  * I338;
    U  * I339;
    U  * I340;
    void * I341;
    U  I342;
    void * I343;
    U  I344;
    U  I345;
    U  I346;
    U  I347;
    U  I348;
    U  I349;
    UP  * I350;
    U  * I351;
    U  * I352;
    U  I353 :15;
    U  I354 :14;
    U  I355 :1;
    U  I356 :1;
    U  I357 :1;
    U  I358 :3;
    U  I359 :1;
    U  I360 :1;
    U  I361 :17;
    U  I362 :3;
    U  I363 :5;
    U  I364 :1;
    U  I365 :1;
    U  I366 :1;
    U  I367 :31;
    struct scope * I368;
    U  I370;
    U  I371;
    U  I372;
    U  * I373;
    U  * I374;
    U  * I375;
    U  I376;
    U  I377;
    U  I378;
    struct pcbt * I379;
    U  I389;
    U  I390;
    U  I391;
    U  I392;
    void * I393;
    void * I394;
    void * I395;
    int I396;
    U  * I397;
    U  I398;
    U  I399;
    U  I400;
    U  I401;
    U  I402;
    U  I403;
    U  I404;
    void * I405;
    UP  * I406;
    U  I407;
    U  I408;
    void * I409;
    U  I410;
    void * I411;
    U  I412;
    void * I413;
    U  I414;
    int (* I415)(void);
    int (* I416)(void);
    void * I417;
    void * I418;
    void * I419;
    U  I420;
    U  I421;
    U  I422;
    U  I423;
    U  I424;
    U  I425;
    char * I426;
    U  I427;
    U  * I428;
    U  I429;
    U  * I430;
    U  I431;
    U  I432;
    U  I433;
    U  I434;
    U  I435;
    U  I436;
    U  * I437;
    U  I438;
    U  I439;
    U  * I440;
    U  I441;
    U  I442;
    U  I443;
    U  * I444;
    char * I445;
    U  I446;
    U  I447;
    U  I448;
    U  I449;
    U  * I450;
    U  * I451;
    U  I452;
    U  * I453;
    U  * I454;
    U  I455;
    U  I456;
    U  I457;
    UP  * I458;
    U  I459;
    U  I460;
    U  I461;
    struct cosim_info * I462;
    U  I464;
    U  * I465;
    U  I466;
    void * I467;
    U  I468;
    U  * I469;
    U  I470;
    U  * I471;
    U  I472;
    U  I473;
    U  * I474;
    U  I475;
    U  * I476;
    U  I477;
    U  * I478;
    U  I479;
    U  I480;
    U  I481;
    U  I482;
    U  I483;
    U  I484;
    U  I485;
    U  I486;
    U  I487;
    U  * I488;
    U  * I489;
    void (* I490)(void);
    U  * I491;
    UP  * I492;
    struct mhdl_outInfo * I493;
    UP  * I495;
    U  I496;
    UP  * I497;
    U  I498;
    void * I499;
    U  * I500;
    void * I501;
    char * I502;
    int (* I503)(void);
    U  * I504;
    char * I505;
    char * I506;
    U  I507;
    U  * I508;
    char * I509;
    U  I510;
    struct regInitInfo * I511;
    UP  * I513;
    U  * I514;
    char * I515;
    U  I516;
    U  I517;
    U  I518;
    U  I519;
    U  I520;
    U  I521;
    U  I522;
    U  I523;
    UP  * I524;
    U  I525;
    U  I526;
    U  I527;
    U  I528;
    UP  * I529;
    U  I530;
    UP  * I531;
    U  I532;
    U  I533;
    U  I534;
    U  * I535;
    U  I536;
    U  I537;
    U  I538;
    U  * I539;
    U  * I540;
    UP  * I541;
    UP  * I542;
    void * I543;
    UP  I544;
    void * I545;
    void * I546;
    void * I547;
    void * I548;
    void * I549;
    UP  I550;
    U  * I551;
    U  * I552;
    void * I553;
    U  I554 :1;
    U  I555 :31;
    U  I556;
    U  I557;
    U  I558;
    int I559;
    U  I560 :1;
    U  I561 :1;
    U  I562 :1;
    U  I563 :29;
    void * I564;
    void * I565;
    void * I566;
    void * I567;
    void * I568;
    UP  * I569;
    U  * I570;
    U  I571;
    char * I572;
    U  * I573;
    U  * I574;
    char * I575;
    int * I576;
    UP  * I577;
    struct etype * I578;
    U  I629;
    U  I630;
    U  I631;
    U  * I632;
    void * I633;
    U  I634;
    U  I635;
    void * I636;
    U  I637;
    U  I638;
    U  * I639;
    U  * I640;
    char * I641;
    U  I642;
    struct covreg_rt * I643;
    U  I645;
    U  I646;
    U  * I647;
    U  I648;
    U  * I649;
    U  I650;
    U  I651;
    U  * I652;
};
typedef struct pcbt {
    U  * I381;
    UP  I382;
    U  I383;
    U  I384;
    U  I385;
    U  I386;
    U  I387;
    U  I388;
} PCBT;
struct iptmpl {
    QIRD  * I720;
    struct vcs_globals_t * I721;
    void * I723;
    UP  I724;
    UP  I725;
    struct iptmpl * I715[2];
};
typedef unsigned long long FileOffset;
typedef struct _RmaMultiInputTable {
    U  I865 :1;
    U  I866 :1;
    U  I660 :2;
    U  I661 :4;
    U  I662 :5;
    U  I867 :1;
    U  I868 :1;
    U  I869 :1;
    U  I870 :1;
    U  I871 :1;
    U  I872 :1;
    U  I873;
    U  I874;
    U  I203;
    U  I875;
    U  I876 :1;
    U  I877 :31;
    union {
        U  utable;
        U  edgeInputNum;
    } I687;
    U  I878 :4;
    U  I879 :4;
    U  I880 :4;
    U  I881 :4;
    U  I882 :4;
    U  I883 :4;
    U  I884 :1;
    U  I885 :1;
    U  I886 :1;
    U  I365 :5;
    HsimExprChar  * I887;
    UB  * I888;
    UB  * I889;
    struct _RmaMultiInputTable * I864;
    struct _RmaMultiInputTable * I891;
} RmaMultiInputTable;
typedef struct _HsCgPeriod {
    U  I937;
    U  I938;
} HsCgPeriod;
typedef struct {
    U   I939[2];
    U  I940 :1;
    U  I941 :1;
    U  I942 :8;
    U  I943 :8;
    U  I944 :8;
    U  I945 :4;
    U  I946 :1;
    U  I947 :1;
    unsigned long long I948;
    unsigned long long I949;
    unsigned long long I950;
    unsigned long long I951;
    unsigned long long I938;
    U  I937;
    U  I952;
    U  I953;
    U  I954;
    U  I955;
    U  I956;
    HsCgPeriod  * I957[10];
} HsimSignalMonitor;
typedef struct {
    FlatNodeNum  I958;
    InstNum  I959;
    U  I897;
    scalar  I960;
    UB  I961;
    UB  I962;
    UB  I963;
    UB  I964;
    U  I965;
    U  I966;
    U  I967;
    U  I968;
    U  I969;
    U  I970;
    U  I971;
    U  I972;
    U  I973;
    HsimSignalMonitor  * I974;
    RP  I975;
    RmaTimeStamp64  I976;
    U  I977;
    RmaTimeStamp64  I978;
    U  I979;
    UB  I980;
} HsimNodeRecord;
typedef struct {
    RP  I981;
    RP  I715;
} RmaIbfIp;
typedef struct {
    RP  I981;
    RP  pcode;
} RmaIbfPcode;
typedef struct {
    RmaEblk  I712;
} RmaEvTriggeredOrSyncLoadCg;
typedef struct {
    RO  I861;
    RP  pcode;
} SchedGateFanout;
typedef struct {
    RO  I861;
    RP  pcode;
    U   I918[4];
} SchedSelectGateFanout;
typedef struct {
    RP  pcode;
    RmaEblklq  I712;
} SchedGateEblk;
typedef struct {
    RP  pcode;
    RmaEblklq  I712;
    UB  * I982;
} SchedSelectGateEblk;
typedef struct {
    RP  I983;
    RP  pfn;
    RP  pcode;
} RmaSeqPrimOutputEblkData;
typedef struct {
    RmaEblk  I712;
    RP  I984;
} RmaAnySchedSampleSCg;
typedef struct {
    RmaEblk  I712;
    RP  I982;
    RP  I984;
    vec32  I985;
} RmaAnySchedVCg;
typedef struct {
    RmaEblk  I712;
    RP  I982;
    RP  I984;
    vec32   I762[1];
} RmaAnySchedWCg;
typedef struct {
    RmaEblk  I712;
    RP  I982;
    RP  I984;
    scalar   I986[1];
} RmaAnySchedECg;
typedef struct {
    U  I987;
    U  I700;
    U  I897;
    U  I988;
    RmaIbfIp  * I989;
    EBLK  I712;
    void * val;
} RmaThreadSchedCompiledLoads;
typedef struct {
    U  I700;
    U  I708;
    RmaThreadSchedCompiledLoads  * I990;
} RmaSchedCompileLoadsCg;
typedef struct {
    RP  I991;
} RmaRootCbkCg;
typedef struct {
    RP  I992;
} RmaRootVcdCg;
typedef struct {
    RP  I993;
} RmaRootForceCbkCg;
typedef struct {
    RmaEblk  I712;
    RP  I994;
} RmaForceCbkJmpCg;
typedef struct {
    U  I5;
    U  I708 :30;
    U  I995 :1;
    U  I996 :1;
    vec32  I794;
    U  I997;
    RP  I998;
    RP  I999;
} RmaForceSelectorV;
typedef struct {
    U  I5;
    RmaIbfPcode  I1005;
} RmaNetTypeDriverGate;
typedef struct {
    U  I5;
    U  I656;
    RmaIbfPcode   I1005[1];
} RmaNetTypeScatterGate;
typedef struct {
    U  I5;
    RmaIbfPcode  I1005;
} RmaNetTypeGatherGate;
typedef struct {
    RmaIbfPcode  I1006;
    U  I1007 :3;
    U  I1008 :1;
    U  I1009 :1;
    U  I874 :16;
} RmaNbaGateOfn;
typedef struct {
    U  I5;
    NBS  I1010;
    RmaIbfPcode  I1006;
} RmaNbaGate1;
typedef struct {
    RP  ptable;
    RP  pfn;
    RP  pcode;
} Rma1InputGateFaninCgS;
typedef struct RmaSeqPrimOutputS_ RmaSeqPrimOutputOnClkS;
struct RmaSeqPrimOutputS_ {
    RP  pfn;
    RP  I1013;
    U  state;
    U  I1014;
    RP  I1015;
    U  I694;
    scalar  val;
};
typedef struct {
    U  I5;
    U  iinput;
    UB  I1017;
    RP  I1018;
} RmaCondOptLoad;
typedef struct {
    U  I5;
    U  iinput;
    UB  I1017;
    RP  I1018;
} RmaMacroStateUpdate;
typedef struct {
    U  I5;
    U  state;
    U  I1019;
    UB  I1017;
    U  * I1020;
} RmaMacroState;
typedef struct {
    U  iinput;
    RP  I1021;
} RmaMultiInputLogicGateCg;
typedef struct {
    U  iinput;
    RP  ptable;
    RP  I1021;
} RmaSeqPrimEdgeInputCg;
typedef struct {
    RmaEblk  I712;
    RP  pcode;
} RmaSched0GateCg;
typedef struct {
    RmaEblk  I712;
    RP  pcode;
    RP  pfn;
} RmaUdpDeltaGateCg;
typedef struct {
    RmaEblk  I712;
    RP  pcode;
    RP  pfn;
    scalar  I1022;
} RmaSchedDeltaGateCg;
typedef struct {
    UB  I1023;
    RP  I1024;
    RP  I1025;
} RmaPropNodeSeqLhsSCg;
typedef struct {
    RmaEblk  I712;
    RP  pcode;
    U  I897;
    U   I701[1];
} RmaBitEdgeEblk;
typedef struct {
    U  I5;
    RP  I793;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaGateDelay;
typedef struct {
    U  I5;
    RP  I793;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaGateBehavioralDelay;
typedef struct {
    U  I5;
    union {
        RP  I1250;
        RP  I1532;
        RP  I1546;
    } I767;
    RmaIbfPcode  I1006;
} RmaMPDelay;
typedef struct {
    U  I5;
    RmaPulse  I1026;
    RmaIbfPcode  I1006;
} RmaMPPulseHybridDelay;
typedef struct {
    U  I5;
    RmaIbfPcode  I1006;
    RmaMps  I1027;
} RmaMPHybridDelay;
typedef struct {
    U  I5;
    U  I1028;
    RmaIbfPcode  I1006;
    RmaEblk  I752;
} RmaMPHybridDelayPacked;
typedef struct {
    U  I5;
    RmaIbfPcode  I1006;
    RmaMpspNewCsdf  I1029;
} RmaMPPulseDelay;
typedef struct {
    U  I5;
    RmaMpsp  I1029;
    RmaIbfPcode  I1006;
} RmaMPPulseOptHybridDelay;
typedef struct _RmaBehavioralTransportDelay {
    U  I5;
    RP  I673;
    RmaTransEventHdr  I903;
    RP  I790;
    RmaIbfPcode  I1006;
} RmaBehavioralTransportDelayS;
typedef struct {
    U  I5;
    U  I673;
    RmaTransEventHdr  I903;
    RP  I790;
    RmaIbfPcode  I1006;
} RmaNtcTransDelay;
typedef struct {
    U  I5;
    U  I673;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaNtcTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaNtcTransZeroDelay;
typedef struct {
    U  I5;
    U  I1030;
    U  I1031;
    RmaTransEventHdr  I903;
    RP  I790;
    RmaIbfPcode  I1006;
} RmaNtcTransDelayRF;
typedef struct {
    U  I5;
    U  I1030;
    U  I1031;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaNtcTransMpwOptDelayRF;
typedef struct {
    U  I5;
    RP  I1032;
    RmaTransEventHdr  I903;
    RP  I790;
    RmaIbfPcode  I1006;
} RmaICTransDelay;
typedef struct {
    U  I5;
    RP  I1032;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaICTransMpwOptDelay;
typedef struct {
    U  I5;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaICTransZeroDelay;
typedef struct {
    U  I5;
    RP  I793;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaICSimpleDelay;
typedef struct {
    U  I5;
    union {
        RP  psimple;
        RP  I1532;
        RP  I1546;
    } I767;
    RmaIbfPcode  I1006;
} RmaICDelay;
typedef struct {
    U  I5;
    RP  I793;
    RmaEblk  I712;
    RmaIbfPcode  I1006;
} RmaPortDelay;
typedef struct {
    U  I5;
    RP   I1036[(4)];
} RmaRtlXEdgesHdr;
typedef struct {
    U  I5;
    US  I1037;
    US  I365;
    RP  I1038;
    RP  I1039;
    RP  I1040;
} RmaRtlEdgeBlockHdr;
typedef struct {
    RP  I1041;
    RP  I1042;
} RemoteDbsedLoad;
typedef struct {
    RmaEblk  I712;
    RP  I1043;
    RP  I1044;
    U  I1045 :16;
    U  I1046 :2;
    U  I1047 :2;
    U  I365 :12;
    U  I468;
    RP  I1048;
    RP   I797[(4)];
    RP   I799[(4)];
    RemoteDbsedLoad   I1049[1];
} RmaRtlEdgeBlock;
typedef struct TableAssign_ {
    struct TableAssign_ * I864;
    struct TableAssign_ * I784;
    U  I5;
    U  I1051 :1;
    U  I1052 :1;
    U  I1053 :2;
    U  I1054 :1;
    U  I694 :8;
    U  I1055 :1;
    U  I1056 :1;
    U  I1057 :1;
    U  I1058 :1;
    U  I365 :15;
    RP  ptable;
    RP  I1021;
} TableAssign;
typedef struct TableAssignLayoutOnClk_ {
    struct TableAssignLayoutOnClk_ * I864;
    struct TableAssignLayoutOnClk_ * I784;
    U  I5;
    U  I1051 :1;
    U  I1052 :1;
    U  I1053 :2;
    U  I1054 :1;
    U  I694 :8;
    U  I1055 :1;
    U  I1056 :1;
    U  I1057 :1;
    U  I1058 :1;
    U  I365 :15;
    RP  ptable;
    RmaSeqPrimOutputOnClkS  I1060;
    RmaEblk  I712;
} TableAssignLayoutOnClk;
typedef struct {
    RP  pfn;
    U  state;
    U  I1061;
} RmaSeqPrimOutputOnClkOpt;
typedef struct TableAssignLayoutOnClkOpt_ {
    struct TableAssignLayoutOnClkOpt_ * I864;
    struct TableAssignLayoutOnClkOpt_ * I784;
    U  I5;
    U  I1051 :1;
    U  I1052 :1;
    U  I1053 :2;
    U  I1054 :1;
    U  I694 :8;
    U  I1055 :1;
    U  I1056 :1;
    U  I1057 :1;
    U  I1058 :1;
    U  I365 :15;
    U  I1063;
    RmaSeqPrimOutputOnClkOpt  I1060;
    RmaSeqPrimOutputEblkData  I1064;
} TableAssignLayoutOnClkOpt;
typedef struct {
    U  I5;
    RP  I784;
    RP  I1065;
} RmaTableAssignList;
typedef struct {
    U  I5;
    RP  I784;
    RP  I1065;
    RP  I1066;
    RP  I1015;
    US  I694;
    UB  I960;
    UB  I1067;
    UB  I1068;
    UB  I758;
    RP   I1069[0];
} RmaThreadTableAssignList;
typedef struct {
    RP  I1066;
    RP  I1015;
    US  I694;
    UB  I960;
    UB  I1067;
    UB  I1068;
    UB  I758;
} RmaThreadTableHeader;
typedef struct {
    RP  I1041;
} RmaWakeupListCg;
typedef struct {
    RP  I1041;
} RmaWakeupArrayCg;
typedef struct {
    RP  I1041;
    RP  I1070;
} RmaPreCheckWakeupListCg;
typedef struct {
    RP  I1041;
    RP  I1070;
} RmaPreCheckWakeupArrayCg;
typedef struct {
    U  I1071;
    U  I694;
    RmaTimeStamp   I1072[1];
} RmaTsArray;
typedef struct {
    U  iinput;
    RP  I1073;
} RmaConditionsMdb;
typedef struct {
    RP  I1074;
    RP  I1075;
    U  I1076;
} RmaTcListHeader;
typedef struct {
    RP  I864;
    RP  I1077;
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
} RmaTcCoreSimple;
typedef struct {
    RP  I864;
    RP  I1077;
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1088;
} RmaTcCoreConditional;
typedef struct {
    RP  I864;
    RP  I1077;
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1088;
    RP  I1089;
} RmaTcCoreConditionalOpt;
typedef struct {
    RP  I864;
    RP  I1077;
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1089;
    RP  I1090;
    U  I1091;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtc;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
} RmaTcCoreSimpleNoList;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1013;
} RmaTcCoreSimpleNoListMdb;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1088;
} RmaTcCoreConditionalNoList;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1088;
    RP  I1089;
} RmaTcCoreConditionalOptNoList;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1089;
    RP  I1090;
    U  I1091;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoList;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1089;
    RP  I1090;
    RP  I1013;
    U  I1091;
    RmaConditionsMdb   arr[1];
} RmaTcCoreConditionalMtcNoListMdb;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    RP  I1088;
    RP  I1013;
} RmaTcCoreConditionalNoListMdb;
typedef struct {
    RP  I1078;
    RP  I707;
    U  I1079;
    scalar  I874;
    scalar  I1080;
    US  I1081 :1;
    US  I1082 :1;
    US  I1083 :1;
    US  I1084 :1;
    US  I1085 :1;
    US  I1086 :1;
    US  I1087 :5;
    U  I1093;
    RP  I1094;
    RP  I1095;
    RP  I1088;
    RP  I1096;
    RP  I1097;
    RmaTimeStamp  I1098;
} RmaTcCoreNochange;
typedef struct {
    RP  I1099;
    RP  I864;
} RmaTcCoreNochangeList;
typedef struct {
    RP  I1073;
    RmaTimeStamp  I1100;
    scalar  I1101;
} RmaConditionalTSLoadNoList;
typedef struct {
    RP  I864;
    RP  I1073;
    RmaTimeStamp  I1100;
    scalar  I1101;
} RmaConditionalTSLoad;
typedef struct {
    RmaTimeStamp  I1100;
    scalar  I1101;
    US  I874;
    RP  I1089;
} RmaConditionalTSLoadOptNoList;
typedef struct {
    RP  I864;
    RmaTimeStamp  I1100;
    scalar  I1101;
    US  I874;
    RP  I1089;
} RmaConditionalTSLoadOpt;
typedef struct {
    RP  I1089;
    RP  I1102;
    U  I1091;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoList;
typedef struct {
    RP  I1013;
    RP  I1089;
    RP  I1102;
    U  I1091;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtcNoListMdb;
typedef struct {
    RP  I864;
    RP  I1089;
    RP  I1102;
    U  I1091;
    RmaConditionsMdb   arr[1];
} RmaConditionalTSLoadMtc;
typedef struct {
    U  I1103;
    U  I1104;
    FlatNodeNum  I1105;
    U  I897;
    U  I1106;
    U  I1107;
    RmaIbfPcode  I1006;
    union {
        scalar  I1108;
        vec32  I1109;
        scalar  * I1110;
        vec32  * I1111;
    } val;
} RmaScanSwitchData;
typedef struct {
    RP  I864;
    RP  I784;
    RP  I1112;
} RmaDoublyLinkedListElem;
typedef struct {
    RP  I1113;
    U  I1114 :1;
    U  I1115 :1;
    U  I1116 :1;
    U  I1117 :4;
    U  I365 :25;
    U  I1118;
} RmaSwitchGateInCbkListInfo;
typedef struct {
    union {
        RmaDoublyLinkedListElem  I1594;
        RmaSwitchGateInCbkListInfo  I2;
    } I687;
    RmaIbfPcode  I1006;
} RmaSwitchGate;
typedef struct RmaNonEdgeLoadData1_ {
    US  I1119;
    scalar  val;
    scalar  I1120 :1;
    scalar  I1121 :1;
    scalar  I1122 :1;
    scalar  I1123 :1;
    scalar  I1124 :1;
    RP  I797;
    RP  I1125;
    RP  I1105;
    RP  I1126;
    RP  I1127;
} RmaNonEdgeLoadData1;
typedef struct RmaNonEdgeLoadHdr1_ {
    UB  I1120;
    UB  I1128;
    RmaNonEdgeLoadData1  * I1036;
    RmaNonEdgeLoadData1  * I784;
    void * I1129;
} RmaNonEdgeLoadHdr1;
typedef struct RmaChildClockProp_ {
    RP  I797;
    RP  I1130;
    RP  I1105;
    RP  pcode;
    scalar  val;
} RmaChildClockProp;
typedef struct RmaChildClockPropList1_ {
    RmaChildClockProp  * I1036;
    RmaChildClockProp  * I784;
} RmaChildClockPropList1;
typedef struct {
    U  I5;
    U  I1131;
} RmaHDLCosimDUTGate;
struct clock_load {
    U  I181 :5;
    U  I182 :12;
    U  I183 :1;
    U  I184 :2;
    U  I185 :1;
    U  I186 :1;
    U  I187 :1;
    U  I188 :9;
    U  I189;
    U  I190;
    void (* pfn)(void * I192, char val);
};
typedef struct clock_data {
    U  I197 :1;
    U  I198 :1;
    U  I199 :1;
    U  I200 :1;
    U  I181 :5;
    U  I182 :12;
    U  I201 :6;
    U  I202 :1;
    U  I184 :2;
    U  I185 :1;
    U  I188 :1;
    U  I203;
    U  I204;
    U  I205;
    U  I189;
    U  I206;
    U  I207;
    U  I208;
    U  I209;
    U  I210;
} HdbsClockData;
struct clock_hiconn {
    U  I214;
    U  I215;
    U  I189;
    U  I184;
};
typedef struct _RmaDaiCg {
    RP  I1132;
    RP  I1133;
    U  I1134;
} RmaDaiCg;
typedef union _RmaCbkMemOptUnion {
    RP  I1132;
    RP  I1135;
    RP  I1136;
} RmaCbkMemOptUnion;
typedef struct _RmaDaiOptCg {
    RmaCbkMemOptUnion  I1137;
} RmaDaiOptCg;
struct futq_slot2 {
    U  I744;
    U   I745[32];
};
struct futq_slot1 {
    U  I741;
    struct futq_slot2  I742[32];
};
struct futq_info {
    scalar  * I736;
    U  I737;
    U  I738;
    struct futq_slot1  I739[32];
};
struct futq {
    struct futq * I726;
    struct futq * I728;
    RmaEblk  * I729;
    RmaEblk  * I730;
    U  I717;
    U  I1;
};
struct sched_table {
    struct futq * I731;
    struct futq I732;
    struct hash_bucket * I733;
    struct hash_bucket * I735;
};
struct dummyq_struct {
    clock_struct  I1141;
    EBLK  * I1142;
    EBLK  * I1143;
    EBLK  * I1144;
    struct futq * I1145;
    struct futq * I1146;
    struct futq * I1147;
    struct sched_table * I1148;
    struct futq_info * I1150;
    struct futq_info * I1152;
    U  I1153;
    U  I1154;
    U  I1155;
    U  I1156;
    U  I1157;
    U  I1158;
    U  I1159;
    struct millenium * I1160;
    EBLK  * I1162;
    EBLK  * I1163;
    EBLK  * I1164;
    EBLK  * I1165;
    EBLK  * I1166;
    EBLK  * I1167;
    EBLK  * I1168;
    EBLK  * I1169;
    EBLK  * I1170;
    EBLK  * I1171;
    EBLK  * I1172;
    EBLK  * I1173;
    EBLK  * I1174;
    EBLK  * I1175;
    EBLK  * I1176;
    EBLK  * I1177;
    EBLK  * I1178;
    EBLK  * I1179;
    MPS  * I1180;
    struct retain_t * I1181;
    EBLK  * I1182;
    EBLK  * I1183;
    EBLK  * I1184;
    EBLK  * I1185;
    EBLK  * I1186;
    EBLK  * I1187;
    EBLK  * I1188;
    EBLK  * I1189;
    EBLK  * I1190;
    EBLK  * I1191;
    EBLK  * I1192;
    EBLK  * I1193;
    EBLK  * I1194;
    EBLK  * I1195;
    EBLK  * I1196;
    EBLK  * I1197;
    EBLK  * I1198;
    EBLK  * I1199;
    EBLK  * I1200;
    EBLK  * I1201;
    EBLK  * I1202;
    EBLK  * I1203;
    EBLK  * I1204;
    EBLK  * I1205;
    EBLK  * I1206;
    EBLK  * I1207;
    EBLK  I1208;
    EBLK  * I1209;
    EBLK  * I1210;
    EBLK  * I1211;
    EBLK  * I1212;
    int I1213;
    int I1214;
    struct vcs_globals_t * I1215;
    clock_struct  I1216;
    unsigned long long I1217;
    EBLK  * I1218;
    EBLK  * I1219;
    void * I1220;
};
typedef void (* FP)(void *  , scalar   );
typedef void (* FP1)(void *  );
typedef void (* FPRAP)(void *  , vec32  *  , U   );
typedef U  (* FPU1)(void *  );
typedef void (* FPV)(void *  , UB  *  );
typedef void (* FPVU)(void *  , UB  *  , U   );
typedef void (* FPLSEL)(void *  , scalar   , U   );
typedef void (* FPLSELV)(void *  , vec32  *  , U   , U   );
typedef void (* FPFPV)(UB  *  , UB  *  , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPFA)(UB  *  , UB  *  , U   , U   , U   , U   , U   , U   , UB  *  , U   );
typedef void (* FPRPV)(UB  *  , U   , U   , U   );
typedef void (* FPEVCDLSEL)(void *  , scalar   , U   , UB  *  );
typedef void (* FPEVCDLSELV)(void *  , vec32  *  , U   , U   , UB  *  );
typedef void (* FPNTYPE_L)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_H)(void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_LPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , U   );
typedef void (* FPNTYPE_HPAP)(void *  , void *  , void *  , U   , U   , UB  *  , UB  *  , UB  *  , UB  *  , U   );
typedef struct _lqueue {
    EBLK  * I713;
    EBLK  * I1221;
    int I1222;
    struct _lqueue * I755;
} Queue;
typedef struct {
    void * I1224;
    void * I1225;
    void * I1226;
    void * I1227;
    void * I1228;
} ClkLevel;
typedef struct {
    unsigned long long I1229;
    EBLK  I1230;
    U  I1231;
    U  I1232;
    union {
        void * pHeap;
        Queue  * pList;
    } I687;
    unsigned long long I1233;
    ClkLevel  I1234;
    Queue   I1235[1];
} Qhdr;
extern UB   Xvalchg[];
extern UB   X4val[];
extern UB   X3val[];
extern UB   X2val[];
extern UB   XcvtstrTR[];
extern UB   Xcvtstr[];
extern UB   Xbuf[];
extern UB   Xbitnot[];
extern UB   Xwor[];
extern UB   Xwand[];
extern U   Xbitnot4val[];
extern UB   globalTable1Input[];
extern __thread unsigned long long vcs_clocks;
extern UB   Xunion[];
extern U  fRTFrcRelCbk;
extern FP  txpFnPtr;
extern FP   rmaFunctionArray[];
extern UP   rmaFunctionRtlArray[];
extern FP   rmaFunctionLRArray[];
extern U  rmaFunctionCount;
extern U  rmaFunctionLRCount;
extern U  rmaFunctionLRDummyCount;
extern UP  rmaFunctionDummyEndPtr;
extern __thread UB  dummyScalar;
extern __thread UB  fScalarIsForced;
extern __thread UB  fScalarIsReleased;
extern U  fNotimingchecks;
extern U  fFsdbDumpOn;
extern RP  * iparr;
extern FP1  * rmaPostAnySchedFnPtr;
extern FP1  * rmaPostAnySchedFnSamplePtr;
extern FP1  * rmaPostAnySchedVFnPtr;
extern FP1  * rmaPostAnySchedWFnPtr;
extern FP1  * rmaPostAnySchedEFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusFnPtr;
extern FP1  * rmaPostSchedUpdateClockStatusNonCongruentFnPtr;
extern FP1  * rmaPostSchedUpdateEvTrigFnPtr;
extern FP1  * rmaSched0UpdateEvTrigFnPtr;
extern FP1  * rmaPostSchedRecoveryResetDbsFnPtr;
extern U  fGblDataOrTime0Prop;
extern UB   rmaEdgeStatusValArr[];
extern FP1  * propForceCbkSPostSchedCgFnPtr;
extern FP1  * propForceCbkMemoptSPostSchedCgFnPtr;
extern UB  * ptableGbl;
extern U  * vcs_ptableOffsetsGbl;
extern UB  * expandedClkValues;
extern __thread Qhdr  * lvlQueue;
extern __thread unsigned threadIndex;
extern int cPeblkThreads;
extern US   xedges[];
extern U  mhdl_delta_count;
extern U  ignoreSchedForScanOpt;
extern U  fignoreSchedForDeadComboCloud;
extern int fZeroUser;
extern U  fEveBusPullVal;
extern U  fEveBusPullFlag;
extern U  fFutEventPRL;
extern U  fParallelEBLK;
extern U  fBufferingEvent;
extern __thread UB  fNettypeIsForced;
extern __thread UB  fNettypeIsReleased;
extern EBLK  * peblkFutQ1Head;
extern EBLK  * peblkFutQ1Tail;
extern US  * edgeActionT;
extern unsigned long long * derivedClk;
extern U  fHashTableSize;
extern U  fSkipStrChangeOnDelay;
extern U  fHsimTcheckOpt;
extern scalar   edgeChangeLookUp[4][4];
extern U  fDoingTime0Prop;
extern U  fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U  fLoopReportRT;


extern void *mempcpy(void* s1, void* s2, unsigned n);
extern UB* rmaEvalDelays(UB* pcode, scalar val);
extern UB* rmaEvalDelaysV(UB* pcode, vec32* pval);
extern void rmaPopTransEvent(UB* pcode);
extern void rmaSetupFuncArray(UP* ra, U c, U w);
extern void rmaSetupRTLoopReportPtrs(UP* funcs, UP* rtlFuncs, U cnt, U cntDummy, UP end);
extern void SinitHsimPats(void);
extern void VVrpDaicb(void* ip, U nIndex);
extern int SDaicb(void *ip, U nIndex);
extern void SDaicbForHsimNoFlagScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlagStrengthScalar(void* pDaiCb, unsigned char value);
extern void SDaicbForHsimNoFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlag2(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimWithFlag(void* pRmaDaiCg, unsigned char value);
extern void SDaicbForHsimNoFlagFrcRel(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimNoFlagFrcRel2(void* pRmaDaiCg, unsigned char reason, int msb, int lsb, int ndx);
extern void VcsHsimValueChangeCB(void* pRmaDaiCg, void* pValue, unsigned int valueFormat);
extern U isNonDesignNodeCallbackList(void* pRmaDaiCg);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagScalar(void* pDaiCb, unsigned char value, unsigned char isStrength);
extern void VVrpNonEventNonRegdScalarForHsimOptCbkMemopt(void* ip, U nIndex);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptWithFlagDynElabScalar(U* mem, unsigned char value, unsigned char isStrength);
extern void SDaicbForHsimCbkMemOptNoFlagDynElabFrcRel(U* mem, unsigned char reason, int msb, int lsb, int ndx);
extern void SDaicbForHsimCbkMemOptNoFlagFrcRel(void* pDaiCb, unsigned char reason, int msb, int lsb, int ndx);
extern void hsimDispatchCbkMemOptForVcd(RP p, U val);
extern void* hsimGetCbkMemOptCallback(RP p);
extern void hsimDispatchCbkMemOptNoDynElabS(RP* p, U val, U isStrength);
extern void* hsimGetCbkPtrNoDynElab(RP p);
extern void hsimDispatchCbkMemOptDynElabS(U** pvcdarr, U** pcbkarr, U val, U isScalForced, U isScalReleased, U isStrength);
extern void hsimDispatchCbkMemOptNoDynElabVector(RP* /*RmaDaiOptCg* */p, void* pval, U /*RmaValueType*/ vt, U cbits);
extern void copyAndPropRootCbkCgS(RmaRootCbkCg* pRootCbk, scalar val);
extern void copyAndPropRootCbkCgV(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgW(RmaRootCbkCg* rootCbk, vec32* pval);
extern void copyAndPropRootCbkCgE(RmaRootCbkCg* rootCbk, scalar* pval);
extern void dumpRootVcdCg(RmaRootVcdCg* pRootVcd, scalar val);
extern void Wsvvar_callback_non_dynamic1(RP* ptr, int);
extern void rmaExecEvSyncList(RP plist);
extern void Wsvvar_callback_virt_intf(RP* ptr);
extern void Wsvvar_callback_hsim_var(RP* ptr);
extern void checkAndConvertVec32To2State(vec32* value, vec32* svalue, U cbits, U* pforcedBits);
extern unsigned int fGblDataOrTime0Prop;
extern void SchedSemiLerMP1(UB* pmps, U partId);
extern void SchedSemiLerMPO(UB* pmpso, U partId);
extern void rmaDummyPropagate(void);
extern RP rmaTestCg(RP pcode, U vt, UB* value);
extern void hsUpdateModpathTimeStamp(UB* pmps);
extern void doMpd32One(UB* pmps);
extern void doMpdCommon(MPS* pmps);
extern TimeStamp GET_DIFF_DELAY_FUNC(TimeStamp ts);
extern void SchedSemiLerMP(UB* ppulse, U partId);
extern EBLK *peblkFutQ1Head;
extern EBLK *peblkFutQ1Tail;
extern void scheduleuna(UB *e, U t);
extern void scheduleuna_mp(EBLK *e, unsigned t);
extern void schedule(UB *e, U t);
extern void sched_hsopt(struct dummyq_struct * pQ, EBLK *e, U t);
extern void sched_millenium(struct dummyq_struct * pQ, void *e, U thigh, U t);
extern void schedule_1(EBLK *e);
extern void sched0(UB *e);
extern void sched0Raptor(UB *e);
extern void sched0lq(EBLK *e);
extern void sched0lqnc(EBLK *e);
extern void sched0una(UB *e);
extern void sched0una_th(struct dummyq_struct *pq, UB *e);
extern void hsopt_sched0u_th(struct dummyq_struct *pq, UB *e);
extern void scheduleuna_mp_th(struct dummyq_struct *pq, EBLK *e, unsigned t);
extern void schedal(UB *e);
extern void sched0_th(struct dummyq_struct * pQ, EBLK *e);
extern void sched0u(UB *e);
extern void sched0u_th(struct dummyq_struct *pq, UB *e);
extern void sched0_hsim_front_th(struct dummyq_struct * pQ, UB *e);
extern void sched0_hsim_frontlq_th(struct dummyq_struct * pQ, UB *e);
extern void sched0lq_th(struct dummyq_struct * pQ, UB *e);
extern void schedal_th(struct dummyq_struct * pQ, UB *e);
extern void scheduleuna_th(struct dummyq_struct * pQ, void *e, U t);
extern void schedule_th(struct dummyq_struct * pQ, UB *e, U t);
extern void schedule_1_th(struct dummyq_struct * pQ, EBLK *peblk);
extern void SetupLER_th(struct dummyq_struct * pQ, EBLK *e);
extern void FsdbReportClkGlitch(UB*,U);
extern void AddToClkGLitchArray(EBLK*);
extern void SchedSemiLer_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXP_th(struct dummyq_struct * pQ, EBLK *e);
extern void SchedSemiLerTXPFreeVar_th(struct dummyq_struct * pQ, EBLK *e);
extern U getVcdFlags(UB *ip);
extern void VVrpNonEventNonRegdScalarForHsimOpt(void* ip, U nIndex);
extern void VVrpNonEventNonRegdScalarForHsimOpt2(void* ip, U nIndex);
extern void SchedSemiLerTBReactiveRegion(struct eblk* peblk);
extern void SchedSemiLerTBReactiveRegion_th(struct eblk* peblk, U partId);
extern void SchedSemiLerTr(UB* peblk, U partId);
extern void SchedSemiLerNBA(UB* peblk, U partId);
extern void NBA_Semiler(void *ip, void *pNBS);
extern void sched0sd_hsim(UB* peblk);
extern void sched0sd_hsim_PRL(UB* peblk);
extern void sched0lq_parallel_clk(EBLK* peblk);
extern void doFgpRaceCheck(UB* pcode, UB* p, U flag);
extern void doSanityLvlCheck();
extern void sched0lq_parallel_ova(EBLK* peblk);
extern void sched0lq_parallel_ova_precheck(EBLK* peblk);
extern void rmaDlpEvalSeqPrim(UB* peblk, UB val, UB preval);
extern void appendNtcEvent(UB* phdr, scalar s, U schedDelta);
extern void appendTransEventS(RmaTransEventHdr* phdr, scalar s, U schedDelta);
extern void schedRetainHsim(MPS* pMPS, scalar sv, scalar pv);
extern void updateRetainHsim(MPS* pMPS,scalar sv, scalar pv);
extern void hsimCountXEdges(void* record,  scalar s);
extern void hsimRegisterEdge(void* sm,  scalar s);
extern U pvcsGetPartId();
extern void HsimPVCSPartIdCheck(U instNo);
extern void debug_func(U partId, struct dummyq_struct* pQ, EBLK* EblkLastEventx); 
extern struct dummyq_struct* pvcsGetQ(U thid);
extern EBLK* pvcsGetLastEventEblk(U thid);
extern void insertTransEvent(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, int re, UB* predd, U fpdd);
extern void insertNtcEventRF(RmaTransEventHdr* phdr, scalar s, scalar pv, scalar resval, U schedDelta, U* delays);
extern U doTimingViolation(RmaTimeStamp ts,RP* pdata, U fskew, U limit, U floaded, U fcondopt, RmaTimeStamp tsNochange);
extern void sched_gate_hsim(EBLK* peblk, unsigned t, RP* offset, U gd_info, U encodeInPcode, void* propValue);
extern int getCurSchedRegion();
extern FP getRoutPtr(RP, U);
extern U rmaChangeCheckAndUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern void rmaUpdateE(scalar* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaChangeCheckAndUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaLhsPartSelUpdateE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaUpdateWithForceSelectorE(scalar* pvalDst, scalar* pvalSrc, U cbits, U* pforceSelector);
extern void rmaUpdateWFromE(vec32* pvalDst, scalar* pvalSrc, U cbits);
extern U rmaLhsPartSelWithChangeCheckE(scalar* pvalDst, scalar* pvalSrc, U index, U width);
extern void rmaLhsPartSelWFromE(vec32* pvalDst, scalar* pvalSrc, U index,U width);
extern U rmaChangeCheckAndUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateW(vec32* pvalDst, vec32* pvalSrc, U cbits);
extern void rmaUpdateEFromW(scalar* pvalDst, vec32* pvalSrc, U cbits);
extern void *VCSCalloc(size_t size, size_t count);
extern void *VCSMalloc(size_t size);
extern void VCSFree(void *ptr);
extern U rmaLhsPartSelWithChangeCheckW(vec32* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern U rmaLhsPartSelWithChangeCheckEFromW(scalar* pvalDst, vec32* pvalSrc, U index,U width);
extern void rmaLhsPartSelUpdateW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void rmaEvalWunionW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWorW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalWandW(vec32* dst, vec32* src, U cbits, U count);
extern void rmaEvalUnionE(scalar* dst, scalar* src, U cbits, U count, RP ptable);
typedef U RmaCgFunctionType;
extern RmaIbfPcode* rmaEvalPartSelectsW(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWLe32(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsWToE(vec32* pvec32, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern RmaIbfPcode* rmaEvalPartSelectsEToE(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce, UB* pevcdStatus);
extern RmaIbfPcode* rmaEvalPartSelectsEToW(scalar* pv, U startIndex, U onWidth, U offWidth, U count, RmaIbfPcode* pibfPcode, U fnonRootForce);
extern U rmaEvalBitPosEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U VcsForceVecVCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U/*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecVCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecWCg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U/*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType, UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecWCg(UB* pcode, UB* pvDst, U fullcbits, U ibeginDst, U width, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecECg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsForceVecACg(UB* pcode, UB* pval, UB* pvDst, UB* pvCur, U fullcbits, U ibeginSrc, U ibeginDst, U width, U /*RmaValueConvType*/ convtype, U /*RmaForceType*/ frcType,UB* prhs, UB* prhsDst, U frhs, U* pforcedbits, U fisRoot);
extern U VcsReleaseVecCg(UB* pcode, UB* pvDst, U ibeginDst, U width, U /*RmaValueType*/ type,U fisRoot, UB* prhsDst, U frhs, U* pforcedbits);
extern U VcsDriveBitsAndDoChangeCheckV(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckW(vec32* pvSel, vec32* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern U VcsDriveBitsAndDoChangeCheckE(scalar* pvSel, scalar* pvCur, U fullcbits, U* pforcedbits, U isRoot);
extern void cgvecDebug_Eblk(UB* pcode);
extern U rmaCmpW(vec32* pvalDst, vec32* pvalSrc, U index, U width);
extern void copyVec32ArrMask(vec32* pv1, vec32* pv2, U len, U* mask);
extern void* memcpy(void*, const void*, size_t);
extern int memcmp(const void*, const void*, size_t);
extern void propagateScanOptPathVal(EBLK *peblk);
extern UB* rmaProcessScanSwitches(UB* pcode, scalar val);
extern UB* rmaProcessScanSwitchesV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanoptDump(UB* pcode, scalar val);
extern UB* rmaProcessScanoptDumpV(UB* pcode, vec32 *pval);
extern UB* rmaProcessScanChainOptSeqPrims(UB* pcode, scalar val);
extern void rmaProcessPvcsCcn(UB* pcode, scalar val);
extern void rmaProcessPvcsCcnE(UB* pcode, scalar* val);
extern void rmaProcessPvcsCcnW(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnV(UB* pcode, vec32* val);
extern void rmaProcessPvcsCcnCompiledS(UB* pcode, U offset, scalar ibnval);
extern void rmaProcessPvcsCcnCompiledV(UB* pcode, U offset, vec32* pval);
extern void schedResetRecoveryDbs(U cedges, EBLK* peblkFirst);
extern UB* rmaEvalUnaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVOneFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpVLargeFanoutCount(UB* pcode, vec32* pval);
extern UB* rmaEvalAndOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalAndOpV(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVOneFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpVLargeFanoutCount(UB* pcode, vec32* value);
extern UB* rmaEvalOrOpV(UB* pcode, vec32* value);
extern UB* rmaEvalTernaryOpV(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalBinaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalTernaryOpW(UB* pcode, vec32* pval);
extern UB* rmaEvalUnaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalBinaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpE(UB* pcode, scalar* pv);
extern UB* rmaEvalTernaryOpS(UB* pcode, scalar val);
extern scalar rmaGetScalarFromWCg(vec32* pval, U index);
extern void rmaSetScalarInWCg(vec32* pval, U index, scalar s);
extern void rmaCountRaptorBits(void* pval, void* pvalPrev, U cbits, U vt);
extern void setHsimFunc(void* ip);
extern void unsetHsimFunc(void* ip);
extern UB* getEvcdStatusByFlagsE(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsV(vec32* pvec32, UB* pevcdTBDriverFlags, U cdrivers, UB* table, U cbits);
extern UB* getEvcdStatusByFlagsS(scalar* pscalar, UB* pevcdTBDriverFlags, U cdrivers, UB* table);
extern UB* getSingleDrvEvcdStatusS(UB value, U fTBDriver);
extern UB* getSingleDrvEvcdStatusE(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getSingleDrvEvcdStatusV(scalar* pscalars, U fTBDriver, U cbits);
extern UB* getEvcdStatusByDrvEvcdStatus(UB* pdrvevcdStatus, U cdrivers, UB* table, U cbits);
extern void evcdCallback(UP pcode, U cbits);
extern UB* getSavedEvcdStatus(void);
extern void saveEvcdStatus(UB*);
extern void mhdlMarkExport(void*, U);
extern void levelInsertQueue(int);
extern void VcsRciRtl(RP pcode);
extern U fLoopDetectMode;
extern int gFLoopDectCodeEna;
extern U fLoopReportRT;
extern void rtSched0LoopDectDumpProcess(void* e, void* rtn, void* PQ);
extern void pushHsimRtnCtxt(void* pcode);
extern void popHsimRtnCtxt();
extern EBLK* loopReportInlinedSched0Wrapper(EBLK *peblk);
extern void loopReportSched0Wrapper(EBLK *peblk, unsigned int sfType, unsigned int fTH, struct dummyq_struct* pq);
extern void loopReportSchedSemiLerWrapper(EBLK *peblk, int sfType);
extern void CallGraphPushNodeAndAddToGraph(UP flatNode, UP instNum, U dummy);
extern void CallGraphPopNode(void);
extern RP elabGetIpTpl(U in);
extern U rmaEvalBitBothEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQXW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0W(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval01EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval0XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval10EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEval1XEdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX1EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalX0EdgeW(vec32* pvalCurr, vec32* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitPosEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitNegEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitBothEdgeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ1E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitEdgeQ0E(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern U rmaEvalBitChangeE(scalar* pvalCurr, scalar* pvalPrev, U cbits, U* pedges);
extern void rmaScheduleNbaGate(RP pcode, scalar val);
extern void rmaEvalRtlEdgeLoads(RmaRtlEdgeBlockHdr *phdr, US clkEdge, scalar clkVal, scalar prevClkVal, scalar val4,   scalar prevval4, scalar master4val);
extern void rmaEvaluateDynamicGateLoadsCg(RP p, scalar s);
extern void rmaEvaluateFusedWithDynamicGateLoadsCg(RP p, scalar s);
extern void rmaScheduleGatedClockEdgeLoad(UB* p, US* ea, U fNonEdgeLoad, UB* plist, UB* pprevlist, scalar v);
extern void rmaRemoveNonEdgeLoads(UB* pcode);
extern void rmaRecordEvents(HsimNodeRecord *pnr);
extern void handlePCBs(UB* p, U i);
extern void markMasterClkOvaLists(U fdbs, RP p);
extern void rmaChildClockPropAfterWrite(UB* p);
extern void rmaSchedChildClockPropAfterWrite(UB* p, UB* pmasterList, UB val);
extern void HDLCosimProcessDUTInputChange(U inputId, void* val);
extern void rmaChangeListForMovedGates(UB clkVal, UB f10Edge, UB* subMasterVal, UB* plist, RP* p, U count);
extern void rmaEvalSeqPrimLoadsByteArray(UB* pcode, UB val, UB prevval4);
extern void rmaEvalSeqPrimLoadsByteArrayX(UB* pcode, UB val, UB prevval4);
extern void vcsRmaEvalSeqPrimLoadsByteArraySCT(UB* pcode, UB val, UB prevval4, U c);
extern void vcsAbortForBadEBlk(void);
extern scalar edgeChangeLookUp[4][4];
extern void Wsvvar_sched_virt_intf_eval(RP* ptr);
extern void vcs_hwcosim_drive_dut_scalar(uint id, char val);
extern void vcs_hwcosim_drive_dut_vector_4state(uint id, vec32* val);
extern U vcs_rmaGetClkValForSeqUdpLayoutOnClkOpt(UB* poutput);
extern U rmaIsS2State(scalar s);
extern U rmaIsV2State(vec32* pval, U cbits);
extern U rmaIsW2State(vec32* pval, U cbits);
extern U rmaIsE2State(scalar* pval, U cbits);
extern void rmaUpdateRecordFor2State(HsimNodeRecord* record, U f2state);
typedef void (*FuncPtr)();
static inline U asm_bsf (U in)
{
#if defined(linux)
    U out;
#if !defined(__aarch64__)
    asm ("movl %1, %%eax; bsf %%eax, %%eax; movl %%eax, %0;"
        :"=r"(out)
        :"r"(in)
        :"%eax"
        );
#else
    out = ffs(in) - 1;
#endif
    return out;
#else
    return 0;
#endif
}


#ifdef __cplusplus
extern "C" {
#endif
void  hs_0_M_0_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_0_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_0_2__simv_daidir (UB  * pcode);
void  hs_0_M_0_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_1_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_1_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_1_2__simv_daidir (UB  * pcode);
void  hs_0_M_1_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_2_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_2_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_2_2__simv_daidir (UB  * pcode);
void  hs_0_M_3_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_3_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_3_2__simv_daidir (UB  * pcode);
void  hs_0_M_4_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_4_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_4_2__simv_daidir (UB  * pcode);
void  hs_0_M_4_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_5_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_5_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_5_2__simv_daidir (UB  * pcode);
void  hs_0_M_5_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_6_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_6_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_6_2__simv_daidir (UB  * pcode);
void  hs_0_M_7_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_7_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_7_2__simv_daidir (UB  * pcode);
void  hs_0_M_8_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_8_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_8_2__simv_daidir (UB  * pcode);
void  hs_0_M_8_11__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_9_0__simv_daidir (UB  * pcode, scalar  val);
void  hs_0_M_9_1__simv_daidir (UB  * pcode, scalar  val, U  I665, scalar  * I1263, U  did);
void  hs_0_M_9_2__simv_daidir (UB  * pcode);
void  hs_0_M_9_11__simv_daidir (UB  * pcode, scalar  val);
void  hsG_0__0 (struct dummyq_struct * I1249, EBLK  * I1243, U  I673);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
  }
#endif
#endif /*__DO_RMAHDR_*/

