BINARY=coremark
SRC_FILES=core_list_join.c core_state.c core_main.c core_matrix.c core_portme.c core_util.c ee_printf.c 
#util.c
CFLAGS_EXT= -DITERATIONS=1 -DCORE_DEBUG
#-DTOTAL_DATA_SIZE=1200 
#CFLAGS_EXT+= -fstack-protector-all
COPT=-O2

include ../common/Makefile.include
